name: 'CLI Dependency Update'
on:
  workflow_dispatch:
  push:
    branches:
      - gimli01/deps-pr
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NPM_ROBOT_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout npm/node
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          ref: gimli01/deps-pr
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update npm/node
        run: |
          git config user.name "npm-robot"
          git config user.email "ops+robot@npmjs.com"
          npm view npm@latest version --loglevel=silly
          ./tools/update-npm.sh `npm view npm@latest version`
          git push origin gimli01/deps-pr
      - name: Create PR against nodejs/node
        run: |
          gh pr create -R "nodejs/node" -B "master" -H "npm:gimli01/deps-pr" --title "test" --body "test"