name: Create CLI Deps PR

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: ${{ github.repository }}

          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: 'gimli01/deps-pr'

          # Personal access token (PAT) used to fetch the repository. The PAT is configured
          # with the local git config, which enables your scripts to run authenticated git
          # commands. The post-job step removes the PAT.
          #
          # We recommend using a service account with the least permissions necessary. Also
          # when generating a new PAT, select the least scopes necessary.
          #
          # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
          #
          # Default: ${{ github.token }}
          # token: ''

      # - name: Git config
      #   run: |
      #     npm_version=`npm view npm@latest version`
      #     release_branch="gimli01-${npm_version}"
      #     echo "PR_NPM_VERSION=${npm_version} >> $GITHUB_ENV"
      #     echo "PR_RELEASE_BRANCH=${release_branch} >> $GITHUB_ENV"
      #     git remote add downstream https://github.com/nodejs/node.git
      #     git remote add npm git@github.com:npm/node.git
      #     git checkout -b $release_branch
      #     git push --set-upstream origin $release_branch

      # - name: Run update steps
      #   run: |
      #     ./tools/update-npm.sh $PR_NPM_VERSION
      #     git add -A deps/npm
      #     git commit -m "deps: upgrade npm to $PR_NPM_VERSION"
      #     sh ./configure
      #     make -j4
      #     sh ./tools/license-builder.sh
      #     git add .
      #     git commit -m "doc: update npm LICENSE using license-builder.sh"
      #     git rebase --whitespace=fix master

      # - name: Run tests
      #   run: |
      #     make test-npm
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'deps: update npm to v${$PR_NPM_VERSION}'
          committer: npm-robot <ops+robot@npmjs.com>
          base: node/master
          title: "deps: update npm to v${PR_NPM_VERSION}"
          body: |
            This PR was automatically generated by a GitHub Action. Please fill in the description.