name: 'CLI Dependency Workflow'
on:
  push:
    branches:
      - gimli01/deps-pr
jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Update npm/node
        run: |
          gh repo clone npm/node
          gh repo clone npm/cli
          ./node/tools/update-npm.sh `npm view npm@latest version`