name: 'CLI Dependency Workflow'
on:
  push:
    branches:
      - gimli01/deps-pr
jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        run: |
          pwd