name: 'CLI Dependency Update'

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NPM_ROBOT_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout npm/node
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          ref: master
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run dependency updates and create PR
        run: |
          npm_version=`npm view npm@latest version`
          release_branch_name="npm-$npm_version"
          git config user.name "npm-robot"
          git config user.email "ops+robot@npmjs.com"
          git checkout -b "$release_branch_name"
          ./tools/update-npm.sh "$npm_version"
          git push origin "$release_branch_name"
          gh_release_body=`gh release view -R npm/cli`
          gh pr create -R "npm/node" -B "master" -H "npm:$release_branch_name" --title "deps(cli): upgrade npm to $npm_version" --body "$gh_release_body"