name: 'CLI Dependency Update'

on:
  workflow_dispatch:
  push:
    branches:
      - gimli01/deps-pr

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout npm/node
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          ref: master
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run dependency updates and create PR
        run: |
          npm_version=`npm view npm@latest version`
          echo $npm_version
          git config user.name "npm-robot"
          git config user.email "ops+robot@npmjs.com"
          git checkout gimli01/deps-pr
          ./tools/update-npm.sh "$npm_version"
          git push origin gimli01/deps-pr
          gh pr create -R "gimli01/node" -B "master" -H "npm:gimli01/deps-pr" --title "deps(cli): upgrade npm to $version" --body ""