name: 'npm@v6.x.x CLI Dependency Update'

on:
  workflow_dispatch:
    inputs:
      npmVersion:
        description: 'NPM Version'
        required: true
        default: '"6.x.x" or "latest"'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NPM_ROBOT_TOKEN }}
      NPM_VERSION: ${{ github.event.inputs.npmVersion }}
      REPO: 'nodejs/node'
    steps:
      - name: Checkout npm/node
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
          repository: 'nodejs/node'
          token: ${{ secrets.NPM_ROBOT_TOKEN }}
      - name: Run dependency updates and create PR
        run: |
          base_branch=$(( $NPM_VERSION == "master" ? "v14.x-staging"))
          release_branch_name="npm-$NPM_VERSION"
          echo $base_branch
          echo $NPM_VERSION
          echo $release_branch
          git config user.name "npm-robot"
          git config user.email "ops+robot@npmjs.com"
          git checkout -b "$release_branch_name"
          ./tools/update-npm.sh "$NPM_VERSION"
          git push origin "$release_branch_name"
          gh_release_body=`gh release view v"$NPM_VERSION"" -R npm/cli`
          echo $gh_release_body
          gh pr create -R "npm/node" -B "$base_branch" -H "npm:$release_branch_name" --title "deps(cli): upgrade npm to $npm_version" --body "$gh_release_body"
